donar_robot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_caster_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_caster_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_swivel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_swivel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_caster_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_caster_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_swivel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_swivel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
